### ISSUE TITLE
[FEATURE] Add the ability to cancel any transaction by payment agent authority to exchange contracts

### ISSUE THREAD

**Issue by kyken** [BoostryJP/ibet-SmartContract#207]
### 1. Is your feature request related to a problem? Please describe.
- Currently, it is not possible to force the cancellation of an order in an exchange contract, and therefore it is not possible to vest the holder on the vesting date (after changing the status, you have to wait until all settlements are confirmed).

### 2. Describe the solution you'd like
- In exchange contracts, we would like to add a function that allows the paying agent to force the cancellation of orders in process.

**Comment by YoshihitoAso** [comment]
It seems to me that the authority should be given to the agent (payment agent) rather than the issuer.
